# Generated by Django 2.0 on 2019-06-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='department_name',
            field=models.CharField(default='任意部门', max_length=30, verbose_name='部门名'),
        ),
    ]
