# Generated by Django 2.0 on 2019-06-25 16:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='社团描述'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='推送内容'),
        ),
    ]
