# Generated by Django 2.0 on 2019-06-25 16:36

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20190625_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=DjangoUeditor.models.UEditorField(verbose_name='社团描述'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=DjangoUeditor.models.UEditorField(verbose_name='内容'),
        ),
    ]
