# Generated by Django 2.0 on 2019-06-25 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20190625_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='notifications',
        ),
        migrations.AddField(
            model_name='notification',
            name='club',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clubs.Club', verbose_name='社团'),
        ),
    ]
