# Generated by Django 2.0 on 2019-06-26 00:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_auto_20190625_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='create_time',
            field=models.DateField(default=datetime.date.today, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='publish_date',
            field=models.DateField(default=datetime.date.today, verbose_name='发布时间'),
        ),
    ]
