# Generated by Django 2.0 on 2019-06-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_auto_20190626_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/clubs/icons/'),
        ),
    ]
