# Generated by Django 2.0 on 2019-06-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_auto_20190626_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='level',
            field=models.CharField(choices=[('1', '校级'), ('2', '院级'), ('3', '无(特殊用途)')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='club',
            name='type',
            field=models.CharField(choices=[('1', '学术'), ('2', '学艺'), ('3', '体育'), ('4', '服务'), ('5', '康乐'), ('6', '综合'), ('7', '资质'), ('8', '其他'), ('9', '无(特殊用途)')], default=1, max_length=10, verbose_name='社团类型'),
        ),
    ]
