# Generated by Django 2.0 on 2019-06-28 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190626_1327'),
        ('clubs', '0009_auto_20190628_1956'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserClubAdmin',
            new_name='UserClub',
        ),
        migrations.RenameField(
            model_name='userclub',
            old_name='admin',
            new_name='club',
        ),
    ]
