# Generated by Django 2.0 on 2019-06-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_auto_20190628_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='persons',
            field=models.IntegerField(default=0, verbose_name='社团人数'),
        ),
    ]
