# Generated by Django 2.0 on 2019-06-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_club_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='required',
            field=models.CharField(choices=[('1', '大一'), ('2', '大二'), ('3', '不限')], default='1', max_length=2),
        ),
    ]
