# Generated by Django 2.0 on 2019-06-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininfo',
            name='password',
            field=models.CharField(max_length=128, verbose_name='密码'),
        ),
    ]
