# Generated by Django 2.0 on 2019-06-25 09:07

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190623_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='admininfo',
            name='username',
            field=models.CharField(max_length=10, unique=True, validators=[users.validators.validate_username], verbose_name='学号'),
        ),
    ]
