# Generated by Django 2.0 on 2019-06-25 16:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190625_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='简介'),
        ),
    ]
