# Generated by Django 2.0 on 2019-06-25 16:55

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190625_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=DjangoUeditor.models.UEditorField(verbose_name='个人简介'),
        ),
    ]
