# Generated by Django 2.0 on 2019-06-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190626_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='clubs',
            field=models.ManyToManyField(default=None, to='clubs.Club', verbose_name='加入的社团'),
        ),
    ]
